# Terraform remote state storage in Azure
# Auto-generated by bootstrap-azure.sh

terraform {
  backend "azurerm" {
    resource_group_name  = "rg-m365vault-tfstate"
    storage_account_name = "stm365vaulttfstate"
    container_name       = "tfstate"
    key                  = "m365vault.terraform.tfstate"
    use_oidc             = true
  }
}
