"""baseline

Revision ID: fd7fb188f26f
Revises: 
Create Date: 2026-04-09 07:56:29.521965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd7fb188f26f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ms_tenant_id', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('tenant_usage_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('graph_api_calls', sa.Integer(), nullable=True),
    sa.Column('graph_api_throttled', sa.Integer(), nullable=True),
    sa.Column('backup_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('restore_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('storage_bytes_delta', sa.BigInteger(), nullable=True),
    sa.Column('items_backed_up', sa.Integer(), nullable=True),
    sa.Column('items_restored', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'metric_date', name='uq_tenant_metric_date')
    )
    op.create_index(op.f('ix_tenant_usage_metrics_metric_date'), 'tenant_usage_metrics', ['metric_date'], unique=False)
    op.create_index(op.f('ix_tenant_usage_metrics_tenant_id'), 'tenant_usage_metrics', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_tenant_alert_configs_tenant_id'), table_name='tenant_alert_configs')
    op.drop_table('tenant_alert_configs')
    op.create_index(op.f('ix_backup_jobs_parent_job_id'), 'backup_jobs', ['parent_job_id'], unique=False)
    op.create_foreign_key(None, 'backup_jobs', 'backup_jobs', ['parent_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'backup_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_backup_jobs_parent_job_id'), table_name='backup_jobs')
    op.create_table('tenant_alert_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email_recipients', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('webhook_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('enabled_events', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('quiet_start_hour', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quiet_end_hour', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('tenant_alert_configs_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tenant_alert_configs_pkey'))
    )
    op.create_index(op.f('ix_tenant_alert_configs_tenant_id'), 'tenant_alert_configs', ['tenant_id'], unique=True)
    op.drop_index(op.f('ix_tenant_usage_metrics_tenant_id'), table_name='tenant_usage_metrics')
    op.drop_index(op.f('ix_tenant_usage_metrics_metric_date'), table_name='tenant_usage_metrics')
    op.drop_table('tenant_usage_metrics')
    op.drop_table('admin_invites')
    # ### end Alembic commands ###
