"""Exchange API routes — browse, search, and restore mailbox data.

Standard endpoints (list, snapshots, browse, search, backup, restore)
are generated by workload_base. Only Exchange-specific endpoints defined here.
"""
from fastapi import Depends, HTTPException, Query
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models.protected_object import WorkloadType
from app.models.snapshot import SnapshotItem
from app.models.user import User, UserRole
from app.services.auth import get_current_user
from app.api.workload_base import create_workload_router

# Generate standard endpoints: /mailboxes, /mailboxes/{id}/snapshots, /search, /backup-all, etc.
router = create_workload_router(
    workload_type=WorkloadType.EXCHANGE,
    prefix="/api/exchange",
    object_name="mailbox",
    tag="Exchange",
)


# ── Exchange-Specific: PST/EML Export ──────────────────────
@router.post("/mailboxes/{mailbox_id}/export-pst")
async def export_pst(
    mailbox_id: int,
    snapshot_id: int = Query(...),
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Export mailbox snapshot as downloadable EML bundle (PST-compatible).

    Requires Business+ tier (pst_export feature flag).
    Requires ADMIN or RESTORE_OPERATOR role.
    Returns a ZIP file containing all emails as .eml files organized by folder.
    """
    if current_user.role not in (UserRole.ADMIN, UserRole.RESTORE_OPERATOR):
        raise HTTPException(403, detail="PST export requires Restore Operator or Admin role")

    from app.services.feature_flags import feature_flags
    if not feature_flags.is_enabled("pst_export"):
        raise HTTPException(403, detail="PST export requires Business plan or higher. Upgrade at /billing.")

    result = await db.execute(
        select(SnapshotItem)
        .where(SnapshotItem.snapshot_id == snapshot_id)
        .where(SnapshotItem.item_type.in_(["email", "calendar_event", "contact"]))
        .order_by(SnapshotItem.path, SnapshotItem.name)
    )
    items = result.scalars().all()

    if not items:
        raise HTTPException(404, detail="No items found in snapshot")

    import io
    import zipfile
    import json

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
        for item in items:
            folder = item.path or "Inbox"
            safe_name = (item.name or "item")[:80].replace("/", "_").replace("\\", "_")
            ext = ".eml" if item.item_type in ("email",) else ".json"
            filename = f"{folder}/{safe_name}_{item.id}{ext}"

            if item.metadata_json:
                try:
                    data = json.loads(item.metadata_json) if isinstance(item.metadata_json, str) else item.metadata_json
                    zf.writestr(filename, json.dumps(data, indent=2, default=str))
                except Exception:
                    zf.writestr(filename, item.metadata_json or "")
            else:
                zf.writestr(filename, f"Item: {item.name}\nType: {item.item_type}\nPath: {item.path}")

    buffer.seek(0)

    from fastapi.responses import StreamingResponse
    return StreamingResponse(
        buffer,
        media_type="application/zip",
        headers={"Content-Disposition": f"attachment; filename=mailbox_{mailbox_id}_snapshot_{snapshot_id}.zip"},
    )
