"""OneDrive API routes — browse, search, and restore user files.

All standard endpoints generated by workload_base.
No OneDrive-specific endpoints currently needed.
"""
from app.models.protected_object import WorkloadType
from app.api.workload_base import create_workload_router

router = create_workload_router(
    workload_type=WorkloadType.ONEDRIVE,
    prefix="/api/onedrive",
    object_name="account",
    tag="OneDrive",
)
