"""SharePoint API routes — browse, search, and restore site data.

All standard endpoints generated by workload_base.
No SharePoint-specific endpoints currently needed.
"""
from app.models.protected_object import WorkloadType
from app.api.workload_base import create_workload_router

router = create_workload_router(
    workload_type=WorkloadType.SHAREPOINT,
    prefix="/api/sharepoint",
    object_name="site",
    tag="SharePoint",
)
