"""Teams API routes — browse backed-up Teams data.

Standard endpoints generated by workload_base.
Teams-specific: chat user listing, chat message browsing.
"""
import json
from fastapi import Depends, HTTPException, Query
from sqlalchemy import select, func, desc
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models.protected_object import ProtectedObject, WorkloadType
from app.models.snapshot import Snapshot, SnapshotItem, SnapshotStatus, ItemType
from app.models.user import User
from app.services.auth import get_current_user
from app.api.workload_base import create_workload_router

# Generate standard endpoints: /teams, /teams/{id}/snapshots, /search, /backup-all, etc.
router = create_workload_router(
    workload_type=WorkloadType.TEAMS,
    prefix="/api/teams",
    object_name="team",
    tag="Teams",
)


# ── Teams-Specific: Chat Users & Messages ──────────────────
@router.get("/chats")
async def list_chat_users(
    tenant_id: int = Query(...),
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List users with Teams chat backup (user_chats type)."""
    result = await db.execute(
        select(ProtectedObject).where(
            ProtectedObject.tenant_id == tenant_id,
            ProtectedObject.workload_type == WorkloadType.TEAMS,
        ).order_by(ProtectedObject.display_name)
    )
    all_objects = result.scalars().all()

    teams = []
    chat_users = []
    for obj in all_objects:
        metadata = {}
        if obj.metadata_json:
            try:
                metadata = json.loads(obj.metadata_json)
            except (json.JSONDecodeError, TypeError):
                pass
        entry = {
            "id": obj.id,
            "display_name": obj.display_name,
            "ms_object_id": obj.ms_object_id,
            "email": obj.email,
            "status": obj.status.value,
            "last_backup_at": obj.last_backup_at.isoformat() if obj.last_backup_at else None,
            "total_items_backed_up": obj.total_items_backed_up,
            "total_size_bytes": obj.total_size_bytes,
            "type": metadata.get("type", "team"),
        }
        if metadata.get("type") == "user_chats":
            chat_users.append(entry)
        else:
            teams.append(entry)

    return {
        "teams": {"total": len(teams), "items": teams},
        "chats": {"total": len(chat_users), "items": chat_users},
    }


@router.get("/chats/{user_object_id}/messages")
async def list_chat_messages(
    user_object_id: int,
    snapshot_id: int = Query(None),
    search: str = Query(None),
    page_size: int = Query(50, ge=1, le=100),
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Browse backed-up chat messages for a user."""
    obj = await db.get(ProtectedObject, user_object_id)
    if not obj:
        raise HTTPException(status_code=404, detail="User chat object not found")

    if not snapshot_id:
        snap_result = await db.execute(
            select(Snapshot).where(
                Snapshot.protected_object_id == obj.id,
                Snapshot.status == SnapshotStatus.COMPLETED,
            ).order_by(desc(Snapshot.completed_at)).limit(1)
        )
        snap = snap_result.scalar_one_or_none()
        if not snap:
            return {"total": 0, "items": []}
        snapshot_id = snap.id

    stmt = select(SnapshotItem).where(
        SnapshotItem.snapshot_id == snapshot_id,
        SnapshotItem.item_type.in_([ItemType.CHAT_MESSAGE, ItemType.CHAT]),
    )
    if search:
        stmt = stmt.where(SnapshotItem.name.ilike(f"%{search}%"))

    count_stmt = select(func.count()).select_from(stmt.subquery())
    total = (await db.execute(count_stmt)).scalar() or 0

    result = await db.execute(stmt.order_by(SnapshotItem.item_type, SnapshotItem.name).limit(page_size))
    items = result.scalars().all()

    return {
        "total": total,
        "snapshot_id": snapshot_id,
        "items": [
            {
                "id": i.id, "item_type": i.item_type.value,
                "ms_item_id": i.ms_item_id, "name": i.name,
                "path": i.path, "size_bytes": i.size_bytes,
                "metadata": json.loads(i.metadata_json) if i.metadata_json else None,
            }
            for i in items
        ],
    }
